"""empty message

Revision ID: 2388b1e373e8
Revises: 35f3c9fd5c3a
Create Date: 2022-06-03 23:41:11.486732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2388b1e373e8'
down_revision = '35f3c9fd5c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Show', 'Venue', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    # ### end Alembic commands ###
