"""empty message

Revision ID: e13a7873580b
Revises: 2388b1e373e8
Create Date: 2022-06-03 23:48:51.903668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13a7873580b'
down_revision = '2388b1e373e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('Show', sa.Column('veneu_id', sa.Integer(), nullable=False))
    op.drop_constraint('Show_id_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Venue', ['veneu_id'], ['id'])
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('Show_id_fkey', 'Show', 'Venue', ['id'], ['id'])
    op.drop_column('Show', 'veneu_id')
    op.drop_column('Show', 'artist_id')
    # ### end Alembic commands ###
