"""empty message

Revision ID: e489067f7e57
Revises: e13a7873580b
Create Date: 2022-06-03 23:49:47.439216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e489067f7e57'
down_revision = 'e13a7873580b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.drop_constraint('Show_veneu_id_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'])
    op.drop_column('Show', 'veneu_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('veneu_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('Show_veneu_id_fkey', 'Show', 'Venue', ['veneu_id'], ['id'])
    op.drop_column('Show', 'venue_id')
    # ### end Alembic commands ###
